name: sars_cov2_mpro
receptor: protein.pdbqt

box:
  center_x: -18.566
  center_y: -13.513
  center_z: 4.557
  size_x: 28.0
  size_y: 27.306
  size_z: 24.704

pocket:
  contact_cutoff: 3.5
  residue_ids:
    - "A:25"
    - "A:26"
    - "A:27"
    - "A:41"
    - "A:46"
    - "A:49"
    - "A:140"
    - "A:141"
    - "A:142"
    - "A:143"
    - "A:144"
    - "A:145"
    - "A:163"
    - "A:164"
    - "A:165"
    - "A:166"
    - "A:187"
    - "A:188"
    - "A:189"
