from __future__ import annotations

from pathlib import Path

try:
    from rdkit import Chem
    from rdkit.Chem import AllChem, rdMolDescriptors
except ImportError:  # pragma: no cover - dependency check is explicit at runtime
    Chem = None  # type: ignore[assignment]
    AllChem = rdMolDescriptors = None  # type: ignore[assignment]

from biofuzz.molecules.filters import is_drug_like_mol


def meeko_available() -> bool:
    try:
        import meeko  # noqa: F401
    except ImportError:
        return False
    return True


def _embed_with_retries(mol, retries: int = 3) -> bool:
    assert AllChem is not None
    for attempt in range(retries):
        params = AllChem.ETKDGv3()
        params.randomSeed = 0xC0FFEE + attempt
        status = AllChem.EmbedMolecule(mol, params)
        if status == 0:
            return True
    return False


def _optimize_geometry(mol) -> None:
    assert AllChem is not None

    try:
        if AllChem.MMFFHasAllMoleculeParams(mol):
            AllChem.MMFFOptimizeMolecule(mol)
        else:
            AllChem.UFFOptimizeMolecule(mol)
    except Exception:
        # Geometry optimization can fail for edge cases; embedding success is enough
        # for downstream docking attempts.
        return


def _vina_type(atom) -> str:
    atomic_num = atom.GetAtomicNum()
    mapping = {
        1: "HD",
        6: "C",
        7: "N",
        8: "OA",
        9: "F",
        15: "P",
        16: "S",
        17: "Cl",
        35: "Br",
        53: "I",
    }
    return mapping.get(atomic_num, atom.GetSymbol())


def _pdbqt_fallback(mol) -> str:
    assert Chem is not None
    assert rdMolDescriptors is not None

    # Attempt charge assignment; if it fails we still emit 0.0 charges.
    try:
        Chem.rdPartialCharges.ComputeGasteigerCharges(mol)
    except Exception:
        pass

    conf = mol.GetConformer()
    lines = ["REMARK Generated by BioFuzz fallback preparer", "ROOT"]

    for serial, atom in enumerate(mol.GetAtoms(), start=1):
        pos = conf.GetAtomPosition(atom.GetIdx())
        charge_str = atom.GetProp("_GasteigerCharge") if atom.HasProp("_GasteigerCharge") else "0.0"
        try:
            charge = float(charge_str)
        except ValueError:
            charge = 0.0

        atom_name = f"{atom.GetSymbol()}{atom.GetIdx() + 1}"
        atom_type = _vina_type(atom)

        lines.append(
            "ATOM  {serial:5d} {name:<4} LIG A   1    "
            "{x:8.3f}{y:8.3f}{z:8.3f}{occ:6.2f}{temp:6.2f}{charge:7.3f} {atype}".format(
                serial=serial,
                name=atom_name[:4],
                x=pos.x,
                y=pos.y,
                z=pos.z,
                occ=0.00,
                temp=0.00,
                charge=charge,
                atype=atom_type,
            )
        )

    torsdof = int(rdMolDescriptors.CalcNumRotatableBonds(mol))
    lines.append("ENDROOT")
    lines.append(f"TORSDOF {torsdof}")
    return "\n".join(lines) + "\n"


def _pdbqt_with_meeko(mol) -> str | None:
    try:
        from meeko import MoleculePreparation, PDBQTWriterLegacy
    except ImportError:
        return None

    prep = MoleculePreparation()

    try:
        setups = prep.prepare(mol)
    except Exception:
        return None

    # Prefer the setup-based writer path that current Meeko versions recommend.
    if isinstance(setups, list) and setups:
        try:
            text = PDBQTWriterLegacy.write_string(setups[0])
            if isinstance(text, tuple):
                text = text[0]
            if isinstance(text, str) and "TORSDOF" in text:
                return text
        except Exception:
            pass

    # Compatibility with older Meeko releases that still expose a writer on the
    # preparation object.
    if hasattr(prep, "write_pdbqt_string"):
        try:
            text = prep.write_pdbqt_string()
            if isinstance(text, tuple):
                text = text[0]
            if isinstance(text, str) and "TORSDOF" in text:
                return text
        except Exception:
            return None

    return None


def prepare_smiles(
    smiles: str,
    retries: int = 3,
    require_drug_like: bool = True,
    use_meeko: bool = True,
    allow_fallback: bool = False,
    min_mw: float = 0.0,
    max_mw: float = 550.0,
    max_logp: float = 5.0,
    max_hbd: int = 5,
    max_hba: int = 10,
    max_rot_bonds: int = 10,
) -> str | None:
    if Chem is None or AllChem is None:
        return None

    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None

    if require_drug_like and not is_drug_like_mol(
        mol,
        min_mw=min_mw,
        max_mw=max_mw,
        max_logp=max_logp,
        max_hbd=max_hbd,
        max_hba=max_hba,
        max_rot_bonds=max_rot_bonds,
    ):
        return None

    mol = Chem.AddHs(mol)

    if not _embed_with_retries(mol, retries=retries):
        return None

    _optimize_geometry(mol)

    if use_meeko:
        pdbqt = _pdbqt_with_meeko(mol)
        if pdbqt:
            return pdbqt
        if not allow_fallback:
            return None

    return _pdbqt_fallback(mol)


def prepare_smiles_to_file(smiles: str, output_path: str | Path) -> Path | None:
    pdbqt = prepare_smiles(smiles)
    if pdbqt is None:
        return None

    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(pdbqt, encoding="utf-8")
    return path
